spring.application.name=araggoNikaton
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/eaxross_kb060?currentSchema=eaxross_kb060
spring.datasource.username=demo_env_n
spring.datasource.password=demo_env_n
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.web.pageable.serialization-mode=via_dto
